export const freightData = [
  {
    origin: "Antwerp",
    destination: "Alger",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Rotterdam",
    destination: "Alger",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Hamburg",
    destination: "Alger",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Antwerp",
    destination: "Annaba",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Antwerp",
    destination: "Annaba",
    carrier: "MC",
    oceanFreight: 1550,
  },
  {
    origin: "Rotterdam",
    destination: "Annaba",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Hamburg",
    destination: "Annaba",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Antwerp",
    destination: "Skikda",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Rotterdam",
    destination: "Skikda",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Hamburg",
    destination: "Skikda",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Antwerp",
    destination: "Oran",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Rotterdam",
    destination: "Oran",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Hamburg",
    destination: "Oran",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Antwerp",
    destination: "Bejaia",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Rotterdam",
    destination: "Bejaia",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Hamburg",
    destination: "Bejaia",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Antwerp",
    destination: "Djen Djen",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Rotterdam",
    destination: "Djen Djen",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Hamburg",
    destination: "Djen Djen",
    carrier: "MSC",
    oceanFreight: 1650,
  },
  {
    origin: "Antwerp",
    destination: "Tunis",
    carrier: "MSC",
    oceanFreight: 1375,
  },
  {
    origin: "Rotterdam",
    destination: "Tunis",
    carrier: "MSC",
    oceanFreight: 1375,
  },
  {
    origin: "Hamburg",
    destination: "Tunis",
    carrier: "MSC",
    oceanFreight: 1500,
  },
  {
    origin: "Antwerp",
    destination: "Alger",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Rotterdam",
    destination: "Alger",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Hamburg",
    destination: "Alger",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Antwerp",
    destination: "Annaba",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Rotterdam",
    destination: "Annaba",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Hamburg",
    destination: "Annaba",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Antwerp",
    destination: "Skikda",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Rotterdam",
    destination: "Skikda",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Hamburg",
    destination: "Skikda",
    carrier: "CMA CGM",
    oceanFreight: 1125,
  },
  {
    origin: "Antwerp",
    destination: "Sfax",
    carrier: "CMA CGM",
    oceanFreight: 1500,
  },
  {
    origin: "Rotterdam",
    destination: "Sfax",
    carrier: "CMA CGM",
    oceanFreight: 1500,
  },
  {
    origin: "Hamburg",
    destination: "Sfax",
    carrier: "CMA CGM",
    oceanFreight: 1500,
  },
  {
    origin: "Antwerp",
    destination: "Sousse",
    carrier: "CMA CGM",
    oceanFreight: 1500,
  },
  {
    origin: "Rotterdam",
    destination: "Sousse",
    carrier: "CMA CGM",
    oceanFreight: 1500,
  },
  {
    origin: "Hamburg",
    destination: "Sousse",
    carrier: "CMA CGM",
    oceanFreight: 1500,
  },
  {
    origin: "Antwerp",
    destination: "Casablanca",
    carrier: "CMA CGM",
    oceanFreight: 825,
  },
  {
    origin: "Rotterdam",
    destination: "Casablanca",
    carrier: "CMA CGM",
    oceanFreight: 825,
  },
  {
    origin: "Hamburg",
    destination: "Casablanca",
    carrier: "CMA CGM",
    oceanFreight: 825,
  },
  {
    origin: "Antwerp",
    destination: "Misuratra",
    carrier: "MSC",
    oceanFreight: 2050,
  },
  {
    origin: "Rotterdam",
    destination: "Misuratra",
    carrier: "MSC",
    oceanFreight: 2050,
  },
  {
    origin: "Hamburg",
    destination: "Misuratra",
    carrier: "CMA CGM",
    oceanFreight: 1900,
  },
  {
    origin: "Antwerp",
    destination: "Ghazaouet",
    carrier: "CMA CGM",
    oceanFreight: 2000,
  },
  {
    origin: "Hamburg",
    destination: "Ghazaouet",
    carrier: "CMA CGM",
    oceanFreight: 2000,
  },
  {
    origin: "Antwerp",
    destination: "Mombasa",
    carrier: "MSC",
    oceanFreight: 1600,
  },
  {
    origin: "Rotterdam",
    destination: "Mombasa",
    carrier: "MSC",
    oceanFreight: 1600,
  },
  {
    origin: "Hamburg",
    destination: "Mombasa",
    carrier: "MSC",
    oceanFreight: 1600,
  },
  {
    origin: "Antwerp",
    destination: "Dar es Salam",
    carrier: "MSC",
    oceanFreight: 1600,
  },
  {
    origin: "Rotterdam",
    destination: "Dar es Salam",
    carrier: "MSC",
    oceanFreight: 1600,
  },
  {
    origin: "Hamburg",
    destination: "Dar es Salam",
    carrier: "MSC",
    oceanFreight: 1600,
  },
  {
    origin: "Antwerp",
    destination: "Tema",
    carrier: "CMA CGM",
    oceanFreight: 1385,
  },
  {
    origin: "Rotterdam",
    destination: "Tema",
    carrier: "CMA CGM",
    oceanFreight: 1385,
  },
  {
    origin: "Hamburg",
    destination: "Tema",
    carrier: "CMA CGM",
    oceanFreight: 1385,
  },
  {
    origin: "Antwerp",
    destination: "Abidjan",
    carrier: "CMA CGM",
    oceanFreight: 1385,
  },
  {
    origin: "Rotterdam",
    destination: "Abidjan",
    carrier: "CMA CGM",
    oceanFreight: 1385,
  },
  {
    origin: "Hamburg",
    destination: "Abidjan",
    carrier: "CMA CGM",
    oceanFreight: 1385,
  },
  {
    origin: "Antwerp",
    destination: "Dakar",
    carrier: "CMA CGM",
    oceanFreight: 1600,
  },
  {
    origin: "Rotterdam",
    destination: "Dakar",
    carrier: "CMA CGM",
    oceanFreight: 1600,
  },
  {
    origin: "Hamburg",
    destination: "Dakar",
    carrier: "CMA CGM",
    oceanFreight: 1600,
  },
  {
    origin: "Antwerp",
    destination: "Lome",
    carrier: "MSC",
    oceanFreight: 2525,
  },
  {
    origin: "Rotterdam",
    destination: "Lome",
    carrier: "Grimaldi",
    oceanFreight: 2925,
  },
  {
    origin: "Hamburg",
    destination: "Lome",
    carrier: "Grimaldi",
    oceanFreight: 2925,
  },
  {
    origin: "Antwerp",
    destination: "Douala",
    carrier: "MSC",
    oceanFreight: 2400,
  },
  {
    origin: "Rotterdam",
    destination: "Douala",
    carrier: "MSC",
    oceanFreight: 2400,
  },
  {
    origin: "Hamburg",
    destination: "Douala",
    carrier: "MSC",
    oceanFreight: 2450,
  },
  {
    origin: "Antwerp",
    destination: "Lagos/Tincan",
    carrier: "MSC",
    oceanFreight: 1800,
  },
  {
    origin: "Rotterdam",
    destination: "Lagos/Tincan",
    carrier: "MSC",
    oceanFreight: 1800,
  },
  {
    origin: "Hamburg",
    destination: "Lagos/Tincan",
    carrier: "MSC",
    oceanFreight: 1835,
  },
  {
    origin: "Antwerp",
    destination: "Lekki",
    carrier: "CMA CGM",
    oceanFreight: 1575,
  },
  {
    origin: "Rotterdam",
    destination: "Lekki",
    carrier: "CMA CGM",
    oceanFreight: 1575,
  },
  {
    origin: "Hamburg",
    destination: "Lekki",
    carrier: "CMA CGM",
    oceanFreight: 1575,
  },
  {
    origin: "Antwerp",
    destination: "Apapa",
    carrier: "CMA CGM",
    oceanFreight: 1625,
  },
  {
    origin: "Rotterdam",
    destination: "Apapa",
    carrier: "CMA CGM",
    oceanFreight: 1625,
  },
  {
    origin: "Hamburg",
    destination: "Apapa",
    carrier: "CMA CGM",
    oceanFreight: 1625,
  },
  {
    origin: "Antwerp",
    destination: "Luanda",
    carrier: "CMA CGM",
    oceanFreight: 1675,
  },
  {
    origin: "Rotterdam",
    destination: "Luanda",
    carrier: "CMA CGM",
    oceanFreight: 1675,
  },
  {
    origin: "Hamburg",
    destination: "Luanda",
    carrier: "CMA CGM",
    oceanFreight: 1675,
  },
  {
    origin: "Antwerp",
    destination: "Monrovia",
    carrier: "Grimaldi",
    oceanFreight: 3700,
  },
  {
    origin: "Rotterdam",
    destination: "Monrovia",
    carrier: "Grimaldi",
    oceanFreight: 3700,
  },
  {
    origin: "Hamburg",
    destination: "Monrovia",
    carrier: "Grimaldi",
    oceanFreight: 3700,
  },
  {
    origin: "Antwerp",
    destination: "Durban",
    carrier: "MSC",
    oceanFreight: 1000,
  },
  {
    origin: "Rotterdam",
    destination: "Durban",
    carrier: "MSC",
    oceanFreight: 1000,
  },
  {
    origin: "Hamburg",
    destination: "Durban",
    carrier: "MSC",
    oceanFreight: 1125,
  },
  {
    origin: "Antwerp",
    destination: "Cape Town",
    carrier: "MSC",
    oceanFreight: 1000,
  },
  {
    origin: "Rotterdam",
    destination: "Cape Town",
    carrier: "MSC",
    oceanFreight: 1000,
  },
  {
    origin: "Hamburg",
    destination: "Cape Town",
    carrier: "MSC",
    oceanFreight: 1125,
  },
  {
    origin: "Antwerp",
    destination: "Port Elisabeth",
    carrier: "MSC",
    oceanFreight: 1000,
  },
  {
    origin: "Rotterdam",
    destination: "Port Elisabeth",
    carrier: "MSC",
    oceanFreight: 1000,
  },
  {
    origin: "Hamburg",
    destination: "Port Elisabeth",
    carrier: "MSC",
    oceanFreight: 1125,
  },
  {
    origin: "Antwerp",
    destination: "Agadir",
    carrier: "Maersk",
    oceanFreight: 1100,
  },
  {
    origin: "Rotterdam",
    destination: "Agadir",
    carrier: "Maersk",
    oceanFreight: 1100,
  },
  {
    origin: "Hamburg",
    destination: "Agadir",
    carrier: "Maersk",
    oceanFreight: 1100,
  },
  {
    origin: "Antwerp",
    destination: "Tanger",
    carrier: "CMA CGM",
    oceanFreight: 900,
  },
  {
    origin: "Rotterdam",
    destination: "Tanger",
    carrier: "CMA CGM",
    oceanFreight: 900,
  },
  {
    origin: "Hamburg",
    destination: "Tanger",
    carrier: "CMA CGM",
    oceanFreight: 900,
  },
  {
    origin: "Hamburg",
    destination: "Tanger",
    carrier: "MSC",
    oceanFreight: 800,
  },
];

export const spainFreightData = [
  { destination: "Alexandria", carrier: "MAERSK", oceanFreight: 215 },
  { destination: "Damietta", carrier: "ONE", oceanFreight: 410 },
  { destination: "Port Said", carrier: "HAPAG", oceanFreight: 420 },
  { destination: "El Dhekeila", carrier: "ONE", oceanFreight: 410 },
  { destination: "Beirut", carrier: "CMA", oceanFreight: 530 },
  {
    destination: "Haifa- No Direct Service",
    carrier: "HAPAG",
    oceanFreight: 1110,
  },
  { destination: "Misurata", carrier: "CMA", oceanFreight: 665 },
  { destination: "Limassol", carrier: "COSCO", oceanFreight: 735 },
  { destination: "Casablanca", carrier: "MAERSK", oceanFreight: 310 },
  { destination: "Tangier", carrier: "MAERSK", oceanFreight: 290 },
  { destination: "Agadir", carrier: "MAERSK", oceanFreight: 1200 },
  { destination: "Latakia", carrier: "MAERSK", oceanFreight: 940 },
  { destination: "Mersin", carrier: "MAERSK", oceanFreight: 150 },
  { destination: "Iskenderum", carrier: "MAERSK", oceanFreight: 380 },
  { destination: "Izmit", carrier: "MAERSK", oceanFreight: 150 },
  { destination: "Istanbul", carrier: "MAERSK", oceanFreight: 150 },
  { destination: "Izmir Aliaga", carrier: "MAERSK", oceanFreight: 150 },
  { destination: "Gemlik", carrier: "MAERSK", oceanFreight: 150 },
  { destination: "Piraeus", carrier: "MAERSK", oceanFreight: 265 },
  { destination: "Thessaloniki", carrier: "MAERSK", oceanFreight: 380 },
  { destination: "Sousse", carrier: "CMA", oceanFreight: 865 },
  { destination: "Bizerte", carrier: "CMA", oceanFreight: 955 },
  { destination: "Rades", carrier: "CMA", oceanFreight: 855 },
  { destination: "Sfax", carrier: "CMA", oceanFreight: 855 },
  { destination: "Alger", carrier: "CMA", oceanFreight: 1090 },
  { destination: "Oran", carrier: "CMA", oceanFreight: 1120 },
  { destination: "Skidda", carrier: "CMA", oceanFreight: 1280 },
  { destination: "Bejaia", carrier: "CMA", oceanFreight: 1120 },
  { destination: "Djen Djen", carrier: "CMA", oceanFreight: 1280 },
  { destination: "Annaba", carrier: "CMA", oceanFreight: 1280 },
  { destination: "Mostaganen", carrier: "CMA", oceanFreight: 1120 },
  { destination: "Alger", carrier: "WHITE LINES", oceanFreight: 1050 },
  { destination: "Oran", carrier: "WHITE LINES", oceanFreight: 1050 },
  { destination: "Skidda", carrier: "WHITE LINES", oceanFreight: 1290 },
  { destination: "Annaba", carrier: "WHITE LINES", oceanFreight: 1290 },
  { destination: "Jeddah", carrier: "HAPAG", oceanFreight: 600 },
  { destination: "Jebel Ali", carrier: "HAPAG", oceanFreight: 575 },
  { destination: "King Abdullah", carrier: "MSC", oceanFreight: 930 },
  { destination: "Dammam", carrier: "HAPAG", oceanFreight: 580 },
  { destination: "Abu Dhabi", carrier: "MSC", oceanFreight: 540 },
  { destination: "Salalah", carrier: "HAPAG", oceanFreight: 890 },
  { destination: "Colombo", carrier: "MSC", oceanFreight: 665 },
  { destination: "Aqaba", carrier: "HAPAG", oceanFreight: 890 },
  { destination: "Doha", carrier: "MSC", oceanFreight: 570 },
  { destination: "Shuaiba", carrier: "MSC", oceanFreight: 645 },
  { destination: "Sohar", carrier: "MSC", oceanFreight: 645 },
  { destination: "Hazira", carrier: "MSC", oceanFreight: 255 },
  { destination: "Nava Sheva", carrier: "MAERSK", oceanFreight: 220 },
  { destination: "Mundra", carrier: "MAERSK", oceanFreight: 210 },
  { destination: "Ennore Chennai", carrier: "MAERSK", oceanFreight: 440 },
  { destination: "Tuticorin", carrier: "MAERSK", oceanFreight: 590 },
  { destination: "Haldia", carrier: "MSC", oceanFreight: 1020 },
  { destination: "Kolkata", carrier: "MSC", oceanFreight: 920 },
  { destination: "Port Qassim", carrier: "MSC", oceanFreight: 1040 },
  { destination: "Karachi", carrier: "ONE", oceanFreight: 405 },
  { destination: "Umm Qassar", carrier: "MSC", oceanFreight: 1190 },
  { destination: "Bangkok", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Danang", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Haiphong", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Hochiming", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Jakarta", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Laem Chabang", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Penang", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Port Klang", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Semarang", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Surabaya", carrier: "MSC/MAERSK", oceanFreight: 20 },
  { destination: "Shanghai", carrier: "MSC/MAERSK", oceanFreight: 25 },
  {
    destination: "Tianjin/Xingang/Yantian",
    carrier: "MSC/MAERSK",
    oceanFreight: 25,
  },
  { destination: "Qingdao", carrier: "MSC/MAERSK", oceanFreight: 25 },
  { destination: "Ningbo", carrier: "MSC/MAERSK", oceanFreight: 25 },
  { destination: "Mombasa", carrier: "MESSINA", oceanFreight: 1615 },
  { destination: "Dar Es Salaam", carrier: "MESSINA", oceanFreight: 1950 },
  { destination: "Durban", carrier: "MESSINA", oceanFreight: 1300 },
  { destination: "Capetown", carrier: "MSC", oceanFreight: 1590 },
  { destination: "Abidjan", carrier: "OOCL", oceanFreight: 975 },
  { destination: "Tema", carrier: "OOCL", oceanFreight: 1225 },
  { destination: "Dakar", carrier: "OOCL", oceanFreight: 950 },
  { destination: "Cotonou", carrier: "MAERSK", oceanFreight: 1465 },
  { destination: "Lome", carrier: "MAERSK", oceanFreight: 1435 },
  { destination: "Conacky", carrier: "HAPAG", oceanFreight: 1540 },
  { destination: "Luanda", carrier: "HAPAG", oceanFreight: 1550 },
  { destination: "Apapa/Tincan VLC", carrier: "HAPAG", oceanFreight: 1455 },
  { destination: "Apapa/Tincan BCN", carrier: "HAPAG", oceanFreight: 1815 },
  { destination: "Douala VLC", carrier: "GRIMALDI", oceanFreight: 2295 },
  { destination: "Douala", carrier: "CMA", oceanFreight: 2920 },
  { destination: "Libreville VLC", carrier: "GRIMALDI", oceanFreight: 1810 },
  { destination: "Libreville BCN", carrier: "GRIMALDI", oceanFreight: 2050 },
  { destination: "Buenos Aires", carrier: "HAPAG", oceanFreight: 200 },
  { destination: "Santos", carrier: "HAPAG", oceanFreight: 110 },
  { destination: "Montevideo", carrier: "HAPAG", oceanFreight: 120 },
  { destination: "Callao", carrier: "CMA", oceanFreight: 1610 },
  { destination: "Guayaquil", carrier: "CMA", oceanFreight: 1610 },
  { destination: "Paita", carrier: "CMA", oceanFreight: 1610 },
  { destination: "Posorja", carrier: "CMA", oceanFreight: 1610 },
  { destination: "Caucedo", carrier: "CMA", oceanFreight: 1945 },
  { destination: "San Antonio", carrier: "CMA", oceanFreight: 1610 },
  { destination: "Cartagena", carrier: "CMA", oceanFreight: 1610 },
  { destination: "Buenaventura", carrier: "HAPAG", oceanFreight: 2075 },
  { destination: "Arica", carrier: "HAPAG", oceanFreight: 2375 },
  { destination: "Rio de Janeiro", carrier: "HAPAG", oceanFreight: 60 },
  { destination: "Altamira", carrier: "CMA", oceanFreight: 2165 },
  { destination: "Veracruz", carrier: "CMA", oceanFreight: 2165 },
  { destination: "La Guaira", carrier: "HAPAG", oceanFreight: 3240 },
  { destination: "Puerto Cabello", carrier: "HAPAG", oceanFreight: 3240 },
  { destination: "Acajutla", carrier: "HAPAG", oceanFreight: 2190 },
  { destination: "Buenaventura NOR", carrier: "HAPAG", oceanFreight: 1420 },
  { destination: "Callao NOR", carrier: "HAPAG", oceanFreight: 1540 },
  { destination: "Guayaquil NOR", carrier: "HAPAG", oceanFreight: 1400 },
  { destination: "Posorja NOR", carrier: "HAPAG", oceanFreight: 1355 },
  { destination: "San Antonio NOR", carrier: "HAPAG", oceanFreight: 1355 },
];

export const usaFreightData = [
  {
    origin: "New Orleans",
    destination: "Aqaba",
    carrier: "MSC",
    oceanFreight: 4775,
  },
  {
    origin: "New Orleans",
    destination: "Dammam",
    carrier: "MSC",
    oceanFreight: 2525,
  },
  {
    origin: "New Orleans",
    destination: "Dammam",
    carrier: "MSC",
    oceanFreight: 3250,
  },
  {
    origin: "New Orleans",
    destination: "Dammam",
    carrier: "Evergreen",
    oceanFreight: 2450,
  },
  {
    origin: "New Orleans",
    destination: "Dammam",
    carrier: "Evergreen",
    oceanFreight: 2850,
  },
  {
    origin: "New Orleans",
    destination: "Jeddah",
    carrier: "MSC",
    oceanFreight: 4525,
  },
  {
    origin: "New Orleans",
    destination: "Oran",
    carrier: "MSC",
    oceanFreight: 3075,
  },
  {
    origin: "New Orleans",
    destination: "Oran",
    carrier: "MSC",
    oceanFreight: 3150,
  },
  {
    origin: "Houston",
    destination: "Aqaba",
    carrier: "MSC",
    oceanFreight: 4450,
  },
  {
    origin: "Houston",
    destination: "Dammam",
    carrier: "MSC",
    oceanFreight: 2375,
  },
  {
    origin: "Houston",
    destination: "Dammam",
    carrier: "MSC",
    oceanFreight: 2900,
  },
  {
    origin: "Houston",
    destination: "Jeddah",
    carrier: "MSC",
    oceanFreight: 4150,
  },
  {
    origin: "Savannah",
    destination: "Abidjan",
    carrier: "OOCL",
    oceanFreight: 2100,
  },
  {
    origin: "Savannah",
    destination: "Abidjan",
    carrier: "CMA CGM",
    oceanFreight: 2700,
  },
  {
    origin: "Savannah",
    destination: "Abidjan",
    carrier: "MSC",
    oceanFreight: 2350,
  },
  {
    origin: "Savannah",
    destination: "Abidjan",
    carrier: "Maersk",
    oceanFreight: 2000,
  },
  {
    origin: "Savannah",
    destination: "Abidjan",
    carrier: "Hapag",
    oceanFreight: 2400,
  },
  {
    origin: "Savannah",
    destination: "Agadir",
    carrier: "MSC",
    oceanFreight: 2475,
  },
  {
    origin: "Savannah",
    destination: "Alexandria",
    carrier: "OOCL",
    oceanFreight: 950,
  },
  {
    origin: "Savannah",
    destination: "Alexandria",
    carrier: "Cosco",
    oceanFreight: 1125,
  },
  {
    origin: "Savannah",
    destination: "Algiers",
    carrier: "MSC",
    oceanFreight: 2650,
  },
  {
    origin: "Savannah",
    destination: "Algiers",
    carrier: "CMA CGM",
    oceanFreight: 2250,
  },
  {
    origin: "Savannah",
    destination: "Algiers",
    carrier: "Cosco",
    oceanFreight: 1900,
  },
  {
    origin: "Savannah",
    destination: "Algiers",
    carrier: "ONE",
    oceanFreight: 2100,
  },
  {
    origin: "Savannah",
    destination: "Annaba",
    carrier: "MSC",
    oceanFreight: 2700,
  },
  {
    origin: "Savannah",
    destination: "Annaba",
    carrier: "CMA CGM",
    oceanFreight: 2350,
  },
  {
    origin: "Savannah",
    destination: "Apapa/Tin Can Island",
    carrier: "CMA CGM",
    oceanFreight: 2650,
  },
  {
    origin: "Savannah",
    destination: "Apapa/Tin Can Island",
    carrier: "MSC",
    oceanFreight: 3075,
  },
  {
    origin: "Savannah",
    destination: "Apapa/Tin Can Island",
    carrier: "Hapag",
    oceanFreight: 2800,
  },
  {
    origin: "Savannah",
    destination: "Aqaba",
    carrier: "Hapag",
    oceanFreight: 3100,
  },
  {
    origin: "Savannah",
    destination: "Aqaba",
    carrier: "MSC",
    oceanFreight: 3625,
  },
  {
    origin: "Savannah",
    destination: "Aqaba",
    carrier: "Arkas Line",
    oceanFreight: 2375,
  },
  {
    origin: "Savannah",
    destination: "Ashdod",
    carrier: "ONE",
    oceanFreight: 1650,
  },
  {
    origin: "Savannah",
    destination: "Bejaia",
    carrier: "CMA CGM",
    oceanFreight: 2250,
  },
  {
    origin: "Savannah",
    destination: "Bejaia",
    carrier: "MSC",
    oceanFreight: 2700,
  },
  {
    origin: "Savannah",
    destination: "Beirut",
    carrier: "MSC",
    oceanFreight: 1525,
  },
  {
    origin: "Savannah",
    destination: "Cape Town",
    carrier: "ONE",
    oceanFreight: 2250,
  },
  {
    origin: "Savannah",
    destination: "Cape Town",
    carrier: "Maersk",
    oceanFreight: 2550,
  },
  {
    origin: "Savannah",
    destination: "Cape Town",
    carrier: "Hapag",
    oceanFreight: 2565,
  },
  {
    origin: "Savannah",
    destination: "Casablanca",
    carrier: "OOCL",
    oceanFreight: 1550,
  },
  {
    origin: "Savannah",
    destination: "Casablanca",
    carrier: "CMA CGM",
    oceanFreight: 1950,
  },
  {
    origin: "Savannah",
    destination: "Casablanca",
    carrier: "Cosco",
    oceanFreight: 1675,
  },
  {
    origin: "Savannah",
    destination: "Casablanca",
    carrier: "ONE",
    oceanFreight: 2075,
  },
  {
    origin: "Savannah",
    destination: "Casablanca",
    carrier: "MSC",
    oceanFreight: 1825,
  },
  {
    origin: "Savannah",
    destination: "Casablanca",
    carrier: "Sealead",
    oceanFreight: 1400,
  },
  {
    origin: "Savannah",
    destination: "Conakry",
    carrier: "CMA CGM",
    oceanFreight: 3100,
  },
  {
    origin: "Savannah",
    destination: "Dakar",
    carrier: "OOCL",
    oceanFreight: 2125,
  },
  {
    origin: "Savannah",
    destination: "Dakar",
    carrier: "MSC",
    oceanFreight: 2450,
  },
  {
    origin: "Savannah",
    destination: "Dakar",
    carrier: "CMA CGM",
    oceanFreight: 2850,
  },
  {
    origin: "Savannah",
    destination: "Dakar",
    carrier: "Hapag",
    oceanFreight: 2800,
  },
  {
    origin: "Savannah",
    destination: "Dar Es Salaam",
    carrier: "CMA CGM",
    oceanFreight: 2750,
  },
  {
    origin: "Savannah",
    destination: "Dar Es Salaam",
    carrier: "MSC",
    oceanFreight: 3750,
  },
  {
    origin: "Savannah",
    destination: "Dar Es Salaam",
    carrier: "Maersk",
    oceanFreight: 3750,
  },
  {
    origin: "Savannah",
    destination: "Dammam",
    carrier: "MSC",
    oceanFreight: 2350,
  },
  {
    origin: "Savannah",
    destination: "Riyadh",
    carrier: "MSC",
    oceanFreight: 2850,
  },
  {
    origin: "Savannah",
    destination: "Djen Djen",
    carrier: "CMA CGM",
    oceanFreight: 2250,
  },
  {
    origin: "Savannah",
    destination: "Djibouti",
    carrier: "CMA CGM",
    oceanFreight: 4575,
  },
  {
    origin: "Savannah",
    destination: "Djibouti",
    carrier: "Maersk",
    oceanFreight: 4300,
  },
  {
    origin: "Savannah",
    destination: "Douala",
    carrier: "MSC",
    oceanFreight: 3425,
  },
  {
    origin: "Savannah",
    destination: "Douala",
    carrier: "CMA CGM",
    oceanFreight: 3425,
  },
  {
    origin: "Savannah",
    destination: "Durban",
    carrier: "ONE",
    oceanFreight: 2250,
  },
  {
    origin: "Savannah",
    destination: "Durban",
    carrier: "CMA CGM",
    oceanFreight: 2800,
  },
  {
    origin: "Savannah",
    destination: "Durban",
    carrier: "Maersk",
    oceanFreight: 2650,
  },
  {
    origin: "Savannah",
    destination: "Durban",
    carrier: "Hapag",
    oceanFreight: 2950,
  },
  {
    origin: "Savannah",
    destination: "El Khoms",
    carrier: "MSC",
    oceanFreight: 2850,
  },
  {
    origin: "Savannah",
    destination: "El Khoms",
    carrier: "CMA CGM",
    oceanFreight: 2425,
  },
  {
    origin: "Savannah",
    destination: "Jeddah",
    carrier: "MSC",
    oceanFreight: 3500,
  },
  {
    origin: "Savannah",
    destination: "Jeddah",
    carrier: "Sealead",
    oceanFreight: 1700,
  },
  {
    origin: "Savannah",
    destination: "Luanda",
    carrier: "CMA CGM",
    oceanFreight: 3100,
  },
  {
    origin: "Savannah",
    destination: "Luanda",
    carrier: "MSC",
    oceanFreight: 3025,
  },
  {
    origin: "Savannah",
    destination: "Mombasa",
    carrier: "CMA CGM",
    oceanFreight: 2350,
  },
  {
    origin: "Savannah",
    destination: "Mombasa",
    carrier: "CMA CGM",
    oceanFreight: 2500,
  },
  {
    origin: "Savannah",
    destination: "Mombasa",
    carrier: "Maersk",
    oceanFreight: 2100,
  },
  {
    origin: "Savannah",
    destination: "Mombasa",
    carrier: "MSC",
    oceanFreight: 2475,
  },
  {
    origin: "Savannah",
    destination: "Oran",
    carrier: "CMA CGM",
    oceanFreight: 2425,
  },
  {
    origin: "Savannah",
    destination: "Oran",
    carrier: "MSC",
    oceanFreight: 2700,
  },
  {
    origin: "Savannah",
    destination: "Port Louis",
    carrier: "CMA CGM",
    oceanFreight: 4000,
  },
  {
    origin: "Savannah",
    destination: "Shuaiba",
    carrier: "MSC",
    oceanFreight: 2425,
  },
  {
    origin: "Savannah",
    destination: "Skikda",
    carrier: "CMA CGM",
    oceanFreight: 2425,
  },
  {
    origin: "Savannah",
    destination: "Skikda",
    carrier: "MSC",
    oceanFreight: 2750,
  },
  {
    origin: "Savannah",
    destination: "Tamatave",
    carrier: "CMA CGM",
    oceanFreight: 3950,
  },
  {
    origin: "Savannah",
    destination: "Tema",
    carrier: "OOCL",
    oceanFreight: 1950,
  },
  {
    origin: "Savannah",
    destination: "Tema",
    carrier: "CMA CGM",
    oceanFreight: 2150,
  },
  {
    origin: "Savannah",
    destination: "Tema",
    carrier: "MSC",
    oceanFreight: 2825,
  },
  {
    origin: "Savannah",
    destination: "Tema",
    carrier: "Hapag",
    oceanFreight: 2650,
  },
  {
    origin: "Savannah",
    destination: "Sousse",
    carrier: "CMA CGM",
    oceanFreight: 2425,
  },
  {
    origin: "Savannah",
    destination: "Tunis",
    carrier: "CMA CGM",
    oceanFreight: 2400,
  },
  {
    origin: "Savannah",
    destination: "Tunis",
    carrier: "Sealead",
    oceanFreight: 1850,
  },
  {
    origin: "Savannah",
    destination: "Tunis",
    carrier: "MSC",
    oceanFreight: 2600,
  },
];
